### PR TITLE
Fix some issues reported by quantifycode

### PR DESCRIPTION
**Pull request by lucc**

### CODE REVIEW

**Comment by lucc** [comment]
Any reason?

**Comment by wpercy** [comment]
I'm worried it'll mess with some of the commit logs. I went through and I didn't feel that any of them made significant improvements to the readability/functionality of the code.

**Comment by lucc** [comment]
What does it mean that 
> it'll mess with some of the commit logs
?

**Comment by wpercy** [comment]
Sorry, I just mean that it's useful to be able to `git blame` a file and see which commit added a given line. Then you can go to that commit and see who made that change and what they were thinking when they did so. This would obfuscate that commit with a commit that was purely formatting.

**Pull request closed without merging**
