### PR TITLE
Handle pytz timezones in iCalendar serialization

### LINKED ISSUE #32: Serializing iCalendar throws NonExistentTimeError when using pytz timezones
Are pytz timezones meant to be supported for event times when generating an iCalendar?
(This is *probably* the same as the original issue reported in #18.)

The code below throws a `pytz.NonExistentTimeError` in the serialize call, while attempting to automatically generate the VTIMEZONE block for TZID=America/Los_Angeles:

```python
from datetime import datetime
import vobject
import pytz

ical = vobject.iCalendar()
vevent = ical.add('vevent')
vevent.add('dtstart').value = datetime(
    2016, 5, 26, 14, 30, tzinfo=pytz.timezone("America/Los_Angeles"))
ical.serialize()  # NonExistentTimeError: 2000-04-02 02:00:00
```

If not, would pytz support be a reasonable addition to propose? (It seems to be Django's preferred tz source.) Or is there a strong preference for dateutil timezones with vobject?

Python 2.7.11; vobject==0.9.2; python-dateutil==2.5.3; six==1.10.0; pytz==2016.4
```
Traceback (most recent call last):
  File "...lib/python2.7/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "...lib/python2.7/site-packages/vobject/behavior.py", line 152, in serialize
    cls.generateImplicitParameters(obj)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 921, in generateImplicitParameters
    obj.add(TimezoneComponent(tzinfo=getTzid(tzid)))
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 97, in __init__
    self.tzinfo = tzinfo
  File "...lib/python2.7/site-packages/vobject/base.py", line 542, in __setattr__
    prop.fset(self, value)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 171, in settzinfo
    transition = getTransition(transitionTo, year, tzinfo)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 1878, in getTransition
    uncorrected = firstTransition(generateDates(year, month, day), test)
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 1836, in firstTransition
    if not test(dt):
  File "...lib/python2.7/site-packages/vobject/icalendar.py", line 1865, in test
    def test(dt): return tzinfo.dst(dt) != zeroDelta
  File "...lib/python2.7/site-packages/pytz/tzinfo.py", line 447, in dst
    dt = self.localize(dt, is_dst)
  File "...lib/python2.7/site-packages/pytz/tzinfo.py", line 327, in localize
    raise NonExistentTimeError(dt)
NonExistentTimeError: 2000-04-02 02:00:00
```

### PR DESCRIPTION
**Pull request by medmunds**
If pytz is installed, deal with its potential
NonExistentTimeError and AmbiguousTimeError
when serializing a VTIMEZONE.

Fixes #32

### CODE REVIEW

**Comment by medmunds** [comment]
The test case runs only if pytz is installed. I don't really know a good way to handle that with Travis. (Well, other than adding with/without pytz to the Travis matrix, so that every platform runs twice. Let me know if you'd like me to look at that.)

Also, the pytz import in icalendar.py got a little more verbose than I'd like, to keep quantifiedcode happy. If there's some comment pragma to tell QC to ignore a line (like flake8's `# NOQA`), I can clean that up a bit. (I couldn't find one for QC.)

**Comment by medmunds** [comment]
Updated to clear the tzid registry in the new test case. 

(An earlier version of this PR was unfairly blaming `dateutil.tz.gettz` for incorrect tzinfo; the problem was actually unexpected data cached in `icalendar.__tzidMap` by other test cases. Maybe should consider a `TestIcalendar.setUp()` that clears the tzid registry? BTW, testfiles/timezones.ics has pre-2007 data.)

I'm still seeing 28 [timezones where there are differences](https://gist.github.com/medmunds/d519841774414ba21a53d9d180dff9ca) between the VTIMEZONE from pytz and the one from dateutil.tz.gettz (both using tzdb 2016d). I think some of these may be timezones that violate the [assumptions](https://github.com/eventable/vobject/blob/0.9.2/vobject/icalendar.py#L140-L147) in `TimezoneComponent.settzinfo()`, which would be beyond the scope of this PR.

**Comment by untitaker** [comment]
:+1:, this PR fixes the problem I'm encountering at #18

**Comment by liZe** [comment]
@skarim Is there anything we can do help you merge this PR?

**Pull request merged**
